export default {
  UPDATE_USER_INFORMATION_SUCCESS: 'UPDATE_INFORMATION_SUCCESS',
  UPDATE_USER_INFORMATION_FAIL: 'UPDATE_USER_INFORMATION_FAIL',
  UPDATE_USER_ROLE_SUCCESS: 'UPDATE_USER_ROLE_SUCCESS',
  UPDATE_USER_ROLE_FAIL: 'UPDATE_USER_ROLE_FAIL',
  BAN_USER_SUCCESS: 'BAN_USER_SUCCESS',
  BAN_USER_FAIL: 'BAN_USER_FAIL',
  UNBAN_USER_SUCCESS: 'UNBAN_USER_SUCCESS',
  UNBAN_USER_FAIL: 'UNBAN_USER_FAIL'
}